### PR TITLE
PMM-11172 merge with upstream

### PR DESCRIPTION
**Pull request by JiriCtvrtka**

### CODE REVIEW

**Review by ghost — APPROVED** [review]
Too big to review. We shall run integration tests against this version.

**Comment by JiriCtvrtka** [comment]
@michal-kralik I just discussed it with Nurlan and seems our fork doesnt make sense anymore. I will create PR for PMM repo and lets see. Ping you then for review.

**Review by BupycHuk — APPROVED** [review]

**Comment by JiriCtvrtka** [comment]
After changes in PMM repo we dont need our fork anymore. Closing.

**Comment by ghost** [comment]
@JiriCtvrtka @BupycHuk would it make sense to archive this repo and move to the upstream module in `go.mod`?

**Comment by JiriCtvrtka** [comment]
@michal-kralik I already using upstream one in PMM PR and once it will be tested our pg_query_go will be archived.

**Pull request closed without merging**
